=== weblips/m2bookclub/app/code/Umc/Base/etc/umc/form.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
/**
 * Umc_Base extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 *
 * @category  Umc
 * @package   Umc_Base
 * @copyright 2015 Marius Strajeru
 * @license   http://opensource.org/licenses/mit-license.php MIT License
 * @author    Marius Strajeru <ultimate.module.creator@gmail.com>
 */
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="forms">
        <xs:annotation>
            <xs:documentation>Form elements container</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="form" minOccurs="1" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
        <xs:unique name="uniqueFormId">
            <xs:annotation>
                <xs:documentation>Attribute id is unique under all forms</xs:documentation>
            </xs:annotation>
            <xs:selector xpath="form"/>
            <xs:field xpath="@id"/>
        </xs:unique>
    </xs:element>

    <xs:element name="form">
        <xs:annotation>
            <xs:documentation>Form element</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:choice minOccurs="0" maxOccurs="unbounded">
                    <xs:element ref="fieldset" />
                </xs:choice>
            </xs:sequence>
            <xs:attributeGroup ref="formAttributeGroup"/>
        </xs:complexType>
        <xs:unique name="uniqueFieldsetId">
            <xs:annotation>
                <xs:documentation>Attribute id is unique under all fieldsets</xs:documentation>
            </xs:annotation>
            <xs:selector xpath="fieldset"/>
            <xs:field xpath="@id"/>
        </xs:unique>
    </xs:element>

    <xs:element name="fieldset">
        <xs:annotation>
            <xs:documentation>Fieldset settings</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:choice minOccurs="0" maxOccurs="unbounded">
                    <xs:element maxOccurs="1" name="label" type="xs:string" />
                    <xs:element ref="field" />
                </xs:choice>
            </xs:sequence>
            <xs:attributeGroup ref="fieldsetAttributeGroup"/>
        </xs:complexType>
        <xs:unique name="uniqueFieldId">
            <xs:annotation>
                <xs:documentation>Attribute id is unique under all fields</xs:documentation>
            </xs:annotation>
            <xs:selector xpath="field"/>
            <xs:field xpath="@id"/>
        </xs:unique>
    </xs:element>

    <xs:element name="field">
        <xs:annotation>
            <xs:documentation>Field settings</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:choice minOccurs="0" maxOccurs="unbounded">
                    <xs:element maxOccurs="1" name="label" type="xs:string" />
                    <xs:element maxOccurs="1" name="tooltip" type="xs:string" />
                    <xs:element maxOccurs="1" name="source" type="xs:string" />
                    <xs:element maxOccurs="1" name="note" type="xs:string" />
                    <xs:element maxOccurs="1" name="rows" type="xs:int"  minOccurs="0" />
                    <xs:element ref="depends" />
                </xs:choice>
            </xs:sequence>
            <xs:attributeGroup ref="fieldAttributeGroup"/>
        </xs:complexType>
        <xs:unique name="uniqueDependsId">
            <xs:annotation>
                <xs:documentation>Attribute id is unique under all dependency groups</xs:documentation>
            </xs:annotation>
            <xs:selector xpath="depends"/>
            <xs:field xpath="@id"/>
        </xs:unique>
    </xs:element>

    <xs:element name="depends">
        <xs:annotation>
            <xs:documentation>Dependency group settings</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:choice minOccurs="0" maxOccurs="unbounded">
                    <xs:element ref="depend" />
                </xs:choice>
            </xs:sequence>
            <xs:attributeGroup ref="dependsAttributeGroup"/>
        </xs:complexType>
        <xs:unique name="uniqueDependId">
            <xs:annotation>
                <xs:documentation>Attribute id is unique under all dependencies</xs:documentation>
            </xs:annotation>
            <xs:selector xpath="depend"/>
            <xs:field xpath="@id"/>
        </xs:unique>
    </xs:element>

    <xs:element name="depend">
        <xs:annotation>
            <xs:documentation>Dependency settings</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:choice minOccurs="0" maxOccurs="unbounded">
                    <xs:element ref="val" />
                </xs:choice>
            </xs:sequence>
            <xs:attributeGroup ref="dependAttributeGroup"/>
        </xs:complexType>
        <xs:unique name="uniqueValId">
            <xs:annotation>
                <xs:documentation>Attribute id is unique under all dependency values</xs:documentation>
            </xs:annotation>
            <xs:selector xpath="val"/>
            <xs:field xpath="@id"/>
        </xs:unique>
    </xs:element>

    <xs:element name="val">
        <xs:annotation>
            <xs:documentation>Dependency values settings</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute type="xs:string" name="id" use="required"/>
                    <xs:attribute type="xs:boolean" name="disabled" use="optional"/>
                    <xs:attribute type="xs:boolean" name="bool" use="optional"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

    <xs:attributeGroup name="formAttributeGroup">
        <xs:attribute name="id" type="xs:string" use="required" />
    </xs:attributeGroup>



    <xs:attributeGroup name="fieldsetAttributeGroup">
        <xs:attribute name="id" type="xs:string" use="required" />
        <xs:attribute type="xs:int" name="sort" use="optional"/>
        <xs:attribute type="xs:boolean" name="collapsible" use="optional"/>
        <xs:attribute type="xs:string" name="class" use="optional"/>
        <xs:attribute type="xs:string" name="translate" use="optional"/>
    </xs:attributeGroup>

    <xs:attributeGroup name="fieldAttributeGroup">
        <xs:attribute type="xs:string" name="id" use="required"/>
        <xs:attribute type="xs:string" name="type" use="optional"/>
        <xs:attribute type="xs:int" name="sort" use="optional"/>
        <xs:attribute type="xs:boolean" name="required" use="optional"/>
        <xs:attribute type="xs:boolean" name="system" use="optional"/>
        <xs:attribute type="xs:boolean" name="readonly" use="optional"/>
        <xs:attribute type="xs:string" name="class" use="optional"/>
        <xs:attribute type="xs:string" name="reloader-class" use="optional"/>
        <xs:attribute type="xs:string" name="translate" use="optional"/>
    </xs:attributeGroup>

    <xs:attributeGroup name="dependsAttributeGroup">
        <xs:attribute type="xs:string" name="id" use="required"/>
        <xs:attribute type="xs:boolean" name="disabled" use="optional"/>
    </xs:attributeGroup>

    <xs:attributeGroup name="dependAttributeGroup">
        <xs:attribute type="xs:string" name="id" use="required"/>
        <xs:attribute type="xs:boolean" name="disabled" use="optional"/>
        <xs:attribute type="xs:string" name="type" use="optional"/>
    </xs:attributeGroup>
</xs:schema>

=== weblips/m2bookclub/app/code/Umc/Base/etc/umc/form.xml
<?xml version="1.0"?>
<!--
/**
 * Umc_Base extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 *
 * @category  Umc
 * @package   Umc_Base
 * @copyright 2015 Marius Strajeru
 * @license   http://opensource.org/licenses/mit-license.php MIT License
 * @author    Marius Strajeru <ultimate.module.creator@gmail.com>
 */
-->
<forms xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:Umc_Base:etc/umc/form.xsd">
    <form id="umc_settings">
        <fieldset id="settings" sort="10" collapsible="false" translate="label">
            <label>Module Settings</label>
            <field id="qualified" type="select" required="true" sort="10" system="true" translate="label tooltip">
                <label>Fully qualified class names</label>
                <tooltip><![CDATA[If set to Yes then the generated code will have `use` statements at the top of the classes and only use class aliases in the code. If it's set to No then the full class path will be used in the code.]]></tooltip>
                <source>Magento\Config\Model\Config\Source\Yesno</source>
            </field>
            <field id="underscore" type="select" required="true" sort="20" system="true" translate="label tooltip">
                <label>Underscore for protected</label>
                <tooltip><![CDATA[This does not apply for the methods and members that come from the core code.]]></tooltip>
                <source>Magento\Config\Model\Config\Source\Yesno</source>
            </field>
            <field id="annotation" type="select" required="true" sort="30" system="true" translate="label tooltip">
                <label>Add annotations</label>
                <tooltip><![CDATA[If set to yes, then the methods that are magically called from your classes will be added at the top of the class as reference.]]></tooltip>
                <source>Magento\Config\Model\Config\Source\Yesno</source>
            </field>
            <field id="license" type="textarea" required="false" sort="40" system="true" translate="label tooltip">
                <label><![CDATA[License]]></label>
                <tooltip><![CDATA[The text you put here will be added at the top of (almost) each file in the module you create.<br />Use {{Namespace}} as a placeholder for namespace, {{Module}} as a placeholder for the module name and {{Y}} as placeholder for current year.<br />If you don't want any License text on your files just leave this field empty.]]></tooltip>
                <rows>5</rows>
            </field>
        </fieldset>
    </form>
    <form id="umc_module">
        <fieldset id="general" sort="10" collapsible="false" translate="label">
            <label>Module Information</label>
            <field id="namespace" type="text" required="true" sort="10" system="true" translate="label tooltip" class="validate-module-name">
                <label>Namespace</label>
                <tooltip>This is the folder name of your new extension. Your company name should go here. Use only letters and numbers. Start with a capital letter.</tooltip>
            </field>
            <field id="module_name" type="text" required="true" sort="20" system="false" translate="label tooltip" class="validate-module-name">
                <label>Module name</label>
                <tooltip><![CDATA[This is your extension/module name. It should be something meaningful and not very long.<br />Try to use a noun in singular form. Start with a capital letter.]]></tooltip>
            </field>

            <field id="version" type="text" required="true" sort="40" system="true" translate="label tooltip">
                <label>Version</label>
                <tooltip><![CDATA[This is the version of the module.]]></tooltip>
            </field>
            <field id="menu_text" type="text" required="true" sort="50" system="false" translate="label tooltip">
                <label>Admin menu title</label>
                <tooltip><![CDATA[This is the title that will be added to the menu.]]></tooltip>
            </field>
            <field id="menu_parent" type="text" required="false" sort="60" system="false" readonly="true" class="menu-parent-id" translate="label tooltip note">
                <label>Admin parent menu ID</label>
                <tooltip><![CDATA[This is the parent menu id of the module menu. Leave empty to add in top menu.]]></tooltip>
                <note><![CDATA[<a href="#" class="menu-selector-trigger">Select menu parent and position</a>]]></note>
            </field>
            <field id="sort_order" type="text" required="true" sort="70" system="false" readonly="true" class="menu-sort-order" translate="label tooltip note">
                <label>Admin menu sort order</label>
                <tooltip><![CDATA[This is the sort order in the menu.]]></tooltip>
                <note><![CDATA[<a href="#" class="menu-selector-trigger">Select menu parent and position</a>]]></note>
            </field>
        </fieldset>
    </form>
    <form id="umc_entity">
        <fieldset id="name_settings" collapsible="true" sort="10" translate="label">
            <label>Name Settings</label>
            <field id="label_singular" type="text" sort="10" required="true" class="label-singular" translate="label tooltip">
                <label>Label singular</label>
                <tooltip><![CDATA[Each entity must have a label used for buttons, links, messages.<br />This is the singular form of the label. For example in a blog module, the post entity will have the label in singular form 'Post']]></tooltip>
            </field>
            <field id="label_plural" type="text" sort="20" required="true" translate="label tooltip">
                <label>Label plural</label>
                <tooltip><![CDATA[This is the plural form of the label above. It will be used for lists. (For example: 'Posts'). Try to use English words for this label. It's not mandatory, but it makes the taxonomy more readable. UMC will create a language file for the modules it generates and you can translate your module.<br /><span class="label label-info">Info:</span>I recommend the first letter to be uppercase.]]></tooltip>
            </field>
            <field id="name_singular" type="text" sort="30" required="true" class="validate-alphanum validate-code" translate="label tooltip">
                <label>Name singular</label>
                <tooltip><![CDATA[UMC generates the code in a 'human readable' form. It's easier to figure out what the code is about when the variables and methods have a propper name.<br />For example it's easier to read foreach ($_posts as $_post){...} or $_post->getTags() than foreach ($_list as $_item){...} or $_entity->getRelated('tags');<br />The value you fill in here will be used for variable names, file names and table names.]]></tooltip>
            </field>
            <field id="name_plural" type="text" sort="40" required="true" class="validate-alphanum validate-code" translate="label tooltip">
                <label>Name plural</label>
                <tooltip><![CDATA[This is the plural value of the entity code. For example 'posts'.]]></tooltip>
            </field>
        </fieldset>
        <fieldset id="backend_settings" collapsible="true" sort="20">
            <label>Backend settings</label>
            <field id="type" type="select" sort="10" required="true" system="true" reloader-class="entity-reloader attribute-reloader" translate="label tooltip">
                <label>Entity type</label>
                <tooltip><![CDATA[This represents the entity behavior. Flat means one entity instance is mapped to a table row.]]></tooltip>
                <source>Umc\Base\Model\Source\Entity\Type</source>
            </field>
            <field id="is_tree" type="select" sort="20" required="true" system="true" reloader-class="entity-reloader attribute-reloader" translate="label tooltip">
                <label>Behaves as tree</label>
                <tooltip><![CDATA[If set to Yes your entity will have a tree behavior just like the catalog categories do.]]></tooltip>
                <source>Magento\Config\Model\Config\Source\Yesno</source>
            </field>
            <field id="add_created_to_grid" type="select" sort="30" required="true" system="true" translate="label tooltip">
                <label>Add 'Created at' to admin grid</label>
                <tooltip><![CDATA[The entities created with UMC will have a field called 'created_at' with the creation date of any entity instance.<br />If this is set to 'Yes' the 'Created at' field will be added to the admin grid.]]></tooltip>
                <source>\Umc\Base\Model\Source\Attribute\Grid</source>
                <depends id="is_tree">
                    <depend id="is_tree" type="entity">
                        <val id="0">0</val>
                    </depend>
                </depends>
            </field>
            <field id="add_updated_to_grid" type="select" sort="40" required="true" system="true" translate="label tooltip">
                <label>Add 'Updated at' to admin grid</label>
                <tooltip><![CDATA[The entities created with UMC will have a field called 'updated_at' with the last update date of any entity instance.<br />If this is set to 'Yes' the 'Updated at' field will be added to the admin grid.]]></tooltip>
                <source>\Umc\Base\Model\Source\Attribute\Grid</source>
                <depends id="is_tree">
                    <depend id="is_tree" type="entity">
                        <val id="0">0</val>
                    </depend>
                </depends>
            </field>
