=== weblips/m2bookclub/app/code/Umc/Base/etc/umc/save_attributes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
/**
 * Umc_Base extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 *
 * @category  Umc
 * @package   Umc_Base
 * @copyright 2015 Marius Strajeru
 * @license   http://opensource.org/licenses/mit-license.php MIT License
 * @author    Marius Strajeru <ultimate.module.creator@gmail.com>
 */
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="save_attributes">
        <xs:annotation>
            <xs:documentation>All attributes to save</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="entity" minOccurs="1" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
        <xs:unique name="uniqueEntityId">
            <xs:annotation>
                <xs:documentation>Entity id must be unique</xs:documentation>
            </xs:annotation>
            <xs:selector xpath="entity"/>
            <xs:field xpath="@id"/>
        </xs:unique>
    </xs:element>

    <xs:element name="entity">
        <xs:annotation>
            <xs:documentation>Entity mapping</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="attribute" minOccurs="1" maxOccurs="unbounded" />
            </xs:sequence>
            <xs:attributeGroup ref="entityAttributeGroup"/>
        </xs:complexType>
        <xs:unique name="uniqueAttributeId">
            <xs:annotation>
                <xs:documentation>Attribute id is unique under each entity</xs:documentation>
            </xs:annotation>
            <xs:selector xpath="attribute"/>
            <xs:field xpath="@id"/>
        </xs:unique>
    </xs:element>

    <xs:element name="attribute">
        <xs:annotation>
            <xs:documentation>Attribute to save</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute type="xs:string" name="id" use="required"/>
                    <xs:attribute type="xs:boolean" name="disabled" use="optional"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>

    </xs:element>

    <xs:attributeGroup name="entityAttributeGroup">
        <xs:attribute name="id" type="xs:string" use="required" />
    </xs:attributeGroup>

</xs:schema>

=== weblips/m2bookclub/app/code/Umc/Base/etc/umc/save_attributes.xml
<?xml version="1.0"?>
<!--
/**
 * Umc_Base extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 *
 * @category  Umc
 * @package   Umc_Base
 * @copyright 2015 Marius Strajeru
 * @license   http://opensource.org/licenses/mit-license.php MIT License
 * @author    Marius Strajeru <ultimate.module.creator@gmail.com>
 */
-->
<save_attributes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:Umc_Base:etc/umc/save_attributes.xsd">
    <entity id="umc_settings">
        <attribute id="install" />
        <attribute id="license" />
        <attribute id="qualified" />
        <attribute id="underscore" />
        <attribute id="annotation" />
    </entity>
    <entity id="umc_module">
        <attribute id="namespace" />
        <attribute id="module_name" />
        <attribute id="version" />
        <attribute id="menu_text" />
        <attribute id="menu_parent" />
        <attribute id="sort_order" />
    </entity>
    <entity id="umc_entity">
        <attribute id="label_singular" />
        <attribute id="label_plural" />
        <attribute id="name_singular" />
        <attribute id="name_plural" />
        <attribute id="is_tree" />
        <attribute id="add_created_to_grid" />
        <attribute id="add_updated_to_grid" />
        <attribute id="type" />
        <attribute id="search" />
        <attribute id="inline_edit" />
    </entity>
</save_attributes>
